name: My First Pipeline

on:
  push:
    branches: [ "main" ]  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a simple script
        run: echo "Hello, it's my first Pipeline in GitHub Actions."

      - name: Create a dummy artifact
        run: echo "This is a dummy artifact created by the GitHub Actions workflow." > result.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: result.txt