name: Python App CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: CI Step
        run: |
          echo "Checking app structure..."
          if [ -f "ui/app.py" ]; then
            echo "Success: app.py found."
          else
            echo "Error: app.py missing."
            exit 1
          fi

      - name: CD Step
        run: |
          mkdir -p release
          [ -d "ui" ] && cp -r ui/* release/
          echo "Build finished" > release/build_info.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmartSign-Ready-to-Deploy
          path: release/
